### ISSUE TITLE
对于06:移动视角部分代码的疑问

### ISSUE THREAD

**Issue by CregskiN** [MrZz233/tinyrenderer_notes#1]
大佬好！我是看到知乎文章过来的
我注意到你文章和代码中给出的计算 lookAt 的函数：
```c++
Matrix lookat(Vec3f eye, Vec3f center, Vec3f up) {
    Vec3f z = (eye - center).normalize();
    Vec3f x = (up ^ z).normalize();
    Vec3f y = (z ^ x).normalize();
    Matrix rotation = Matrix::identity(4);
    Matrix translation = Matrix::identity(4);
    for (int i = 0; i < 3; i++) {
        rotation[i][3] = -center[i];
    }
    for (int i = 0; i < 3; i++) {
        rotation[0][i] = x[i];
        rotation[1][i] = y[i];
        rotation[2][i] = z[i];
    }
    //这样乘法的效果是先平移物体，再旋转
    Matrix res = rotation*translation;
    return res;
}
```
这样复合了位移和旋转的 rotation，与 M_r * M_t 表示的变换顺序是不同的。前者是先旋转后平移，后者是先平移后旋转。这点在 GAMES101 Lecture 04 8:27 提到过。

所以，假设 lookAt 矩阵生成时，应该先平移后旋转的话，代码应该与 [TinyRenderer](https://github.com/ssloy/tinyrenderer/wiki/Lesson-5:-Moving-the-camera#let-us-create-our-own-glulookat) 原文中给出的伪码差不多：
```c++
void lookat(Vec3f eye, Vec3f center, Vec3f up) {
    Vec3f z = (eye-center).normalize();
    Vec3f x = cross(up,z).normalize();
    Vec3f y = cross(z,x).normalize();
    Matrix Minv = Matrix::identity();
    Matrix Tr   = Matrix::identity();
    for (int i=0; i<3; i++) {
        Minv[0][i] = x[i];
        Minv[1][i] = y[i];
        Minv[2][i] = z[i];
        Tr[i][3] = -eye[i];
    }
    ModelView = Minv*Tr;
}
```

总结一下：
关于 lookAt 的生成，TinyRenderer 文章、GAMES101 的讲解，以及你的注释，都说明 lookAt 矩阵应该表示先平移后旋转，这样得到的 african_head 很小，如下
<img width="810" alt="image" src="https://user-images.githubusercontent.com/53673057/160586863-333fb599-bf9e-4137-a780-f3f54b064028.png">
而 ssloy 的源码、你给出的代码都是只调整 rotation 矩阵其中的元素，我的理解是，这样的矩阵表示先旋转后平移，得到的结果：
<img width="810" alt="image" src="https://user-images.githubusercontent.com/53673057/160587544-154c0992-99f3-4930-ba91-39431b679d11.png">

我的问题是：对于你和 ssloy 代码中只调整 rotation 表示变换的顺序，我是不是理解错了？

ps. 这个问题困扰我又一个下午，还请帮我解答，麻烦你了 :-)

**Comment by CregskiN** [comment]
大乌龙事件！我会错意了！从头到尾的理解都有问题，抱歉啊

**Comment by MrZz233** [comment]
> 
这里的注释在后面章节补全了，tran和rot是分别求逆了，因为物体和摄像机的相对运动是互逆的。然后因为是正交阵，所以可以通过调整元素位置（也就是转置）来实现快速求逆。

**Comment by CregskiN** [comment]
我重新阅读了大佬你的文章和代码，发现我搞混了将world space转换到view space的view矩阵，以及调整摄像机视角的lookAt矩阵。我这画了张图，描述摄像机的变换过程：

![image](https://user-images.githubusercontent.com/53673057/160862758-f5cf66c1-e0d4-48bf-a08f-12ecd348791e.png)


最后想麻烦你检查一下我的理解对不对

**Comment by CregskiN** [comment]
我这边github图片有四分之一加载不出来，不知道你那边能不能看全。这里附上我图床的链接：https://www.qiniu.cregskin.com/202203302242915.png

**Comment by MrZz233** [comment]
> 我重新阅读了大佬你的文章和代码，发现我搞混了将world space转换到view space的view矩阵，以及调整摄像机视角的lookAt矩阵。我这画了张图，描述摄像机的变换过程：
> 
> ![图像](https://user-images.githubusercontent.com/53673057/160862758-f5cf66c1-e0d4-48bf-a08f-12ecd348791e.png)
> 
> 最后想麻烦你检查一下我的理解对不对

对的，摄像机先旋转后平移。
LookAt相当于是封装了一下，让我们只需要输入摄像机位置，摄像机朝向(或者聚焦点)，世界UP，就可以返回这种状态下的摄像机对应的View矩阵的逆。然后将这个View矩阵的逆应用到物体上，就实现了物体从世界空间变换到摄像机空间
